---
title: "Takehome02"
description: |
  Singapore Population Change over Time
author:
  - name: Jiang Mingjun 
    url: https://isss608mj.netlify.app/
    affiliation: Spacely Sprockets
    affiliation_url: https://example.com/spacelysprokets
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    toc: true
    toc_depth: 2

---




```{r setup, include=FALSE}
packages = c('ggiraph', 'plotly', 
             'DT', 'patchwork',
             'gganimate', 'tidyverse',
             'readxl', 'gifski', 'gapminder')
for (p in packages){
  if(!require(p, character.only = T)){
    install.packages(p)
  }
  library(p,character.only = T)
}
```



```{r}
Odata <- read_csv("data/2000to.csv")
Ndata <- read_csv("data/2011to.csv")
```



```{r}

df= Odata %>% full_join(Ndata)

```


```{r}
agetotal <- setNames(aggregate(df$Pop,by=list(AG=df$AG,Sex=df$Sex,Time=df$Time,PA=df$PA),FUN=sum), c("Age","Sex","Time","Planning Area","Population"))

```
```{r}
###sorting AGE in correct order
agetotal$Age<-ordered(agetotal$Age,levels=c("0_to_4","5_to_9","10_to_14","15_to_19","20_to_24","25_to_29","30_to_34","35_to_39","40_to_44","45_to_49","50_to_54","55_to_59","60_to_64","65_to_69","70_to_74","75_to_79","80_to_84","85_to_89","90_and_over"))

```




```{r}
ggplot(agetotal, aes(x = Age, y = Population, fill = Sex)) + 
  geom_bar(data=subset(agetotal,Sex=="Females"),stat = "identity",aes(y=Population/10000)) + 
  geom_bar(data=subset(agetotal,Sex=="Males"),stat="identity",aes(y=Population*(-1)/10000)) + 
  scale_y_continuous(name='Population(unit in 10,000)',breaks=seq(-15,15,1),labels=abs(seq(-15,15,1))) +
  coord_flip()+
  labs(title = 'Year: {as.integer(frame_time)}')+
    transition_time(Time) +
  ease_aes('linear')


```




```{r}
cl<-subset(agetotal, agetotal$`Planning Area` == "Clementi")
ta<-subset(agetotal, agetotal$`Planning Area` == "Tampines")
```
```{r}
ggplot(cl, aes(x = Age, y = Population, fill = Sex)) + 
  geom_bar(data=subset(agetotal,Sex=="Females"),stat = "identity",aes(y=Population/1000)) + 
  geom_bar(data=subset(agetotal,Sex=="Males"),stat="identity",aes(y=Population*(-1)/1000)) + 
  scale_y_continuous(name='Population(unit in 1000) Clementi Area',breaks=seq(-1400,1400,100),labels=abs(seq(-1400,1400,100))) +
  coord_flip()+
  labs(title = 'Year: {as.integer(frame_time)}')+
    transition_time(Time) +
  ease_aes('linear')

```
```{r}
ggplot(ta, aes(x = Age, y = Population, fill = Sex)) + 
  geom_bar(data=subset(agetotal,Sex=="Females"),stat = "identity",aes(y=Population/1000)) +
  geom_bar(data=subset(agetotal,Sex=="Males"),stat="identity",aes(y=Population*(-1)/1000)) + 
  scale_y_continuous(name='Population(unit in 1000) Tampines Area',breaks=seq(-1400,1400,100),labels=abs(seq(-1400,1400,100))) +
  coord_flip()+
  labs(title = 'Year: {as.integer(frame_time)}')+
    transition_time(Time) +
  ease_aes('linear')

```



